config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    },
    controllers: {
      sessions: 'sessions',
      registrations: 'registrations'
    }

  resources :users, :only => [:show]

  devise_scope :user do
    resources :steam_users do
      resources :steam_profile, :steam_friends
    end
    resources :posts, :only => [:create, :index]
  end

end

app/models/steam_user.rb
class SteamUser < ActiveRecord::Base
end

app/controllers/steam_users_controller.rb
class SteamUsersController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_steam_user, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /steam_users
  # GET /steam_users.json
  def index
    @steam_users = SteamUser.all
    render json: @steam_users
  end

  # GET /steam_users/1
  # GET /steam_users/1.json
  def show
    @steam_user = SteamUser.find(params[:id])
    render json: @steam_user
  end

  # GET /steam_users/new
  def new
    @steam_user = SteamUser.new
  end

  # GET /steam_users/1/edit
  def edit
  end

  # POST /steam_users
  # POST /steam_users.json
  def create
    @steam_user = SteamUser.new(steam_user_params)

    respond_to do |format|
      if @steam_user.save
        format.json { render json: @steam_user }
      else
        format.html { render :new }
        format.json { render json: @steam_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steam_users/1
  # PATCH/PUT /steam_users/1.json
  def update
    respond_to do |format|
      if @steam_user.update(steam_user_params)
        format.html { redirect_to @steam_user, notice: 'Steam user was successfully updated.' }
        format.json { render :show, status: :ok, location: @steam_user }
      else
        format.html { render :edit }
        format.json { render json: @steam_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steam_users/1
  # DELETE /steam_users/1.json
  def destroy
    @steam_user.destroy
    respond_to do |format|
      format.html { redirect_to steam_users_url, notice: 'Steam user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_steam_user
      @steam_user = SteamUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def steam_user_params
      params.permit(:user_id, :username, :steamid)
    end
end

app/helpers/steam_users_helper.rb
module SteamUsersHelper
end

app/helpers/steamusers_helper.rb
module SteamusersHelper
end

app/views/steam_users/_form.html.erb
<%= form_for(@steam_user) do |f| %>
  <% if @steam_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@steam_user.errors.count, "error") %> prohibited this steam_user from being saved:</h2>

      <ul>
      <% @steam_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steam_users/edit.html.erb
<h1>Editing Steam User</h1>

<%= render 'form' %>

<%= link_to 'Show', @steam_user %> |
<%= link_to 'Back', steam_users_path %>

app/views/steam_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Steam Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steam_users.each do |steam_user| %>
      <tr>
        <td><%= link_to 'Show', steam_user %></td>
        <td><%= link_to 'Edit', edit_steam_user_path(steam_user) %></td>
        <td><%= link_to 'Destroy', steam_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Steam user', new_steam_user_path %>

app/views/steam_users/new.html.erb
<h1>New Steam User</h1>

<%= render 'form' %>

<%= link_to 'Back', steam_users_path %>

app/views/steam_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_steam_user_path(@steam_user) %> |
<%= link_to 'Back', steam_users_path %>